name: publish

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 1 * *
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}/gollum
      PLATFORMS: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
      BUILD_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/gollum:${{ github.sha}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Buildx Cache
        uses: actions/cache@v2
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx

      - name: Build and push with github sha
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --output "type=image,push=true" \
            --platform "${PLATFORMS}" \
            --pull \
            --tag "${BUILD_TAG}" \
            .

      - name: Basic Test
        run: |
          docker run --rm -d -p "4567:4567" --name test "${BUILD_TAG}"
          sleep 10
          curl -vL -o /dev/null http://localhost:4567
          docker kill test

      - name: Push
        if: success()
        run: |
          GOLLUM_FULL_VERSION=$(docker run --rm "${BUILD_TAG}" gollum --version | cut -d ' ' -f 2)
          GOLLUM_MAJOR_VERSION=$(printf "${GOLLUM_FULL_VERSION}" | cut -d '.' -f 1)
          GOLLUM_MINOR_VERSION=$(printf "${GOLLUM_FULL_VERSION}" | cut -d '.' -f 1-2)
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --output "type=image,push=true" \
            --platform "${PLATFORMS}" \
            --pull \
            --tag "${DOCKERHUB_REPOSITORY}:latest" \
            --tag "${DOCKERHUB_REPOSITORY}:${GOLLUM_FULL_VERSION}" \
            --tag "${DOCKERHUB_REPOSITORY}:${GOLLUM_MAJOR_VERSION}" \
            --tag "${DOCKERHUB_REPOSITORY}:${GOLLUM_MINOR_VERSION}" \
            .

      - name: Update Dockerhub Description
        if: success()
        uses: peter-evans/dockerhub-description@v2.3.1
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
