name: publish

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 1 * *
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Publish
        env:
          DOCKERHUB_REPO: gollum
          PLATFORMS: linux/amd64,linux/arm64
        run: |
          # Build on local architecture and run a very basic curl test
          docker build -t gollum-test .
          docker run --rm -d -p "4567:4567" --name gollum-test gollum-test
          sleep 10
          curl -vL http://localhost:4567
          docker kill gollum-test

          # Grab the gollum version from the test image
          GOLLUM_VERSION=$(docker run --rm gollum-test gollum --version | cut -d ' ' -f 2)

          # Build & push
          docker buildx build --platform "${PLATFORMS}" --push --tag  "${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${GOLLUM_VERSION}" .
